Test infrastructure is now more realistic for storage layout, especially across restart.
MIGRATION TEST NOT WORKING

diff --git a/test/system/test_migration/test b/test/system/test_migration/test
--- a/test/system/test_migration/test
+++ b/test/system/test_migration/test
@@ -102,8 +102,22 @@ test_ws2_to_ws3() {
   cp -rp $TEST_DIR/ws2 $TEST_HOME
   marcel <<EOF
 EOF
-  find $TEST_HOME > $TEST_ARTIFACTS/ws3
+  pushd $TEST_HOME >& /dev/null
+  find . > $TEST_ARTIFACTS/actual
+  pushd $TEST_DIR/ws3 >& /dev/null
+  find . > $TEST_ARTIFACTS/expected
+  popd >& /dev/null
+  check ws2_to_ws3
 }
+
+check() {
+  diff $TEST_ARTIFACTS/expected $TEST_ARTIFACTS/actual > /dev/null
+  if [ $? != '0' ]; then
+    FAILURES=$(($FAILURES+1))
+    echo "Error on $1"
+  fi
+}
+
 
 main() {
   initialize
